---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qwerty.
--- DateTime: 19-3-15 下午6:18
---


function tttt(file_name)
    local file1=io.open(file_name);
    local str = file1:read("*a");
    local i = 1;

    local apis = {};
    local argss = {};

    while i <= #str do
        local word;
        word, i = read_word(str,i);
        local args;
        args, i = read_args(str, i);
        i = skip_white(str, i)
        apis[#apis+1] = word;
        argss[#argss+1] = args;
    end

    local content1 = "#define FUNC_SIZE "..(#apis)
    local content2 = ""
    for i=1,#apis do
        content2 = content2..'"'..apis[i]..'", ';
        --if i%5 == 0 then content2 = content2.."\n"
        --end
    end
    content2 = "const std::vector<std::string> apis_{\n"..content2.."};"
    local content3 = ""
    for i=1,#apis do
        content3 = content3.."#define "..apis[i].."_index "..(i-1)..'\n';
    end
    local content4="#define TEST_BODY "
    for i=1,#apis do
        if i < #apis then
            if 1==i then
                content4 = content4.."CALL("..apis[i]..","..argss[i]..");"..'\\'.."\n"
            else
                content4 = content4.."\t\tCALL("..apis[i]..","..argss[i]..");"..'\\'.."\n"
            end
        else
            content4 = content4.."\t\tCALL("..apis[i]..","..argss[i]..");"
        end
    end

    local content = content1.."\n"..content2.."\n"..content3.."\n"..content4
    print(content)
end
function skip_white(str, pos)
    local c = string.sub(str, pos, pos);
    while "\n" == c do
        pos = pos+1;
        if (pos <= #str) then
            c = string.sub(str, pos, pos);
        else
            break;
        end
    end
    return pos;
end

function read_word(str, pos)
    local start = pos;
    local c = string.sub(str, pos, pos);
    while c ~= "("  do
        pos = pos+1;
        if (pos <= #str) then
            c = string.sub(str, pos, pos);
        else
            break;
        end
    end
    return string.sub(str, start, pos-1), pos;
end

function read_args(str, pos)
    local start = pos;
    local c = string.sub(str, pos, pos);
    while c ~= "\n"  do
        pos = pos+1;
        if (pos <= #str) then
            c = string.sub(str, pos, pos);
        else
            break;
        end
    end
    return string.sub(str, start, pos-1), pos;
end

tttt("tt.txt")